# Generated by Django 5.0.3 on 2024-03-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False)),
                ('Medico_idMedico', models.PositiveIntegerField()),
                ('Paciente_idPaciente', models.PositiveIntegerField()),
                ('Fecha', models.DateField(null=True)),
                ('Hora', models.TimeField(null=True)),
                ('Descripcion', models.TextField(null=True)),
            ],
            options={
                'db_table': 'cita',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField()),
                ('Apellido', models.TextField()),
                ('Especialidad', models.TextField()),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('idPaciente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField()),
                ('Apellido', models.TextField()),
                ('Fecha_Nacimiento', models.DateField(null=True)),
                ('Genero', models.TextField()),
                ('Email', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='PruebaMedica',
            fields=[
                ('idPrueba_Medica', models.AutoField(primary_key=True, serialize=False)),
                ('Medico_idMedico', models.PositiveIntegerField()),
                ('Paciente_idPaciente', models.PositiveIntegerField()),
                ('Tipo', models.TextField()),
                ('Fecha', models.DateField(null=True)),
                ('Resultado', models.TextField()),
            ],
            options={
                'db_table': 'prueba_medica',
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('idTratamiento', models.AutoField(primary_key=True, serialize=False)),
                ('Medico_idMedico', models.PositiveIntegerField()),
                ('Paciente_idPaciente', models.PositiveIntegerField()),
                ('Descripcion', models.TextField()),
                ('Fecha_Inicio', models.DateField(null=True)),
                ('Duracion', models.TextField()),
            ],
            options={
                'db_table': 'tratamiento',
            },
        ),
    ]
