# Generated by Django 5.0.3 on 2024-03-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cita',
            table=None,
        ),
        migrations.AlterModelTable(
            name='medico',
            table=None,
        ),
        migrations.AlterModelTable(
            name='paciente',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pruebamedica',
            table=None,
        ),
        migrations.AlterModelTable(
            name='tratamiento',
            table=None,
        ),
    ]
