# Generated by Django 5.0.3 on 2024-03-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_medico_user_paciente_user_alter_medico_apellido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Apellido',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Fecha_Nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Genero',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_Nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.IntegerField(choices=[(0, 'Otros'), (1, 'M'), (2, 'H')], default=0),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
