# Generated by Django 5.0.3 on 2024-03-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_rename_email_paciente_email_remove_paciente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_Nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
